version: "3.8"
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    ports:
      - "8123:8123" # HTTP
      - "9000:9000" # Native
      - "9009:9009" # debugging
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse

  clickhouse-client:
    image: clickhouse/clickhouse-client
    container_name: clickhouse-client
    command: ["--host", "clickhouse-server"]
    depends_on:
      - clickhouse-server
    stdin_open: true
    tty: true
